terragrunt

diff --git a/.github/workflows/feature.yml b/.github/workflows/feature.yml
--- a/.github/workflows/feature.yml
+++ b/.github/workflows/feature.yml
@@ -2,155 +2,142 @@ name: 'Azure Foundation CI Workflow'
 
 permissions:
   id-token: write
-  contents: write
-  issues: write
-  pull-requests: write
+  contents: read
 
 on:
   push:
     branches:
-      - 'feature**'
-  workflow_call:
-    inputs:
-      runs-on:
-        required: false
-        type: string
-        default: ubuntu-latest
-      infra-working-directory:
-        required: false
-        type: string
-        default: 'infra'
-      infra-terraform-version:
-        required: false
-        type: string
-        default: '1.1.9'
-      environment:
-        required: true
-        type: string
-        default: 'dev'
+      - 'feature/**' # Double asterisks (**) to match any number of characters
 
-    secrets:
-      AZURE_CLIENT_ID:
-        required: true
-      AZURE_SUBSCRIPTION_ID:
-        required: true
-      AZURE_TENANT_ID:
-        required: true
 
 env:
-  ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
-  ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
-  ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
+  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
+  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
+  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
   ARM_USE_OIDC: true
+  ARM_SKIP_PROVIDER_REGISTRATION: true
+
+
 
 jobs:
-
-  terraform-ci:
-    name: 'Terraform CI'
+  build-and-deploy:
     runs-on: ubuntu-latest
-    environment: ${{ inputs.environment }}
-    defaults:
-      run:
-        working-directory: ${{ github.workspace }}/infra
-    env:
-    #this is needed since we are running terraform with read-only permissions
-      ARM_SKIP_PROVIDER_REGISTRATION: true
-    outputs:
-      tfplanExitCode: ${{ steps.tf-plan.outputs.exitcode }}
-      tfplan: ${{ steps.tf-plan.outputs.summary }}
-
     steps:
-    # Checkout the repository to the GitHub Actions runner
-    - name: Checkout
-      uses: actions/checkout@v3
+      - name: 'Az CLI login'
+        uses: azure/login@v1
+        with:
+          client-id: ${{ secrets.AZURE_CLIENT_ID }}
+          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
+          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
 
-    - name: 'az login with oidc'
-      uses: azure/login@v1
-      with:
-        # allow-no-subscriptions: true
-        client-id: ${{ secrets.AZURE_CLIENT_ID }}
-        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
-        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
 
-  # Install the latest version of the Terraform CLI
-    - name: Setup Terraform
-      uses: hashicorp/setup-terraform@v2
-      with:
-        terraform_wrapper: false
-        terraform_version: "1.3.1"
+      - name: Checkout Repository
+        uses: actions/checkout@v2
 
-    - name: Terraform Format
-      run: terraform fmt -check
+      # Install the latest version of the Terraform CLI
+      - name: Setup Terraform
+        uses: hashicorp/setup-terraform@v2
+        with:
+          terraform_version: "1.3.1"
 
-    - name: Check Terraform Backend Configuration and Create if Non-EXISTENT
-      id: check_backend
-      run: |
-        tfstate_file=".terraform/terraform.tfstate"
-        if [ ! -f "$tfstate_file" ]; then
-          # Create RG
-          az group create --name BDOTest1 --location brazilsouth
-          # Create Storage and container
-          az storage account create --name vaaniravinderg01010 --resource-group BDOTest1 --location brazilsouth --sku Standard_LRS --kind StorageV2 --encryption-services blob
-          accountKey=$(az storage account keys list --account-name vaaniravinderg01010 --resource-group BDOTest1 --output tsv --query "[0].value")
-          az storage container create --name containervaani --account-name vaaniravinderg01010 --account-key $accountKey
-          # Enable storage versioning
-          az storage account blob-service-properties update --account-name vaaniravinderg01010 --resource-group BDOTest1 --enable-versioning true
-          echo "::set-output name=accountKey::$accountKey"
-        fi
-      shell: bash
+      - name: Setup Terragrunt
+        run: |
+          sudo wget -q -O /bin/terragrunt "https://github.com/gruntwork-io/terragrunt/releases/download/v0.34.1/terragrunt_linux_amd64"
+          sudo chmod +x /bin/terragrunt
+          terragrunt --version
+          terraform --version
+  
+      - name: 'Init Terraform Backend'
+        id: init-terraform-backend
+        shell: bash
+        run: |
+          pushd ../scripts
+            # Get Repository ID
+            export REPO_ID=$(curl -s -H "Authorization:token ${{ secrets.GIT_TOKEN }}" \
+              https://api.github.com/repos/${{ github.repository }} | jq '.id')
+  
+            # Create tf backend if not exists
+            chmod +x create-tf-backend-azure.sh
+            ./create-tf-backend-azure.sh
+          popd
+        working-directory: ${{ github.workspace }}/infra  
 
-    - name: Initialize Terraform Backend
-      env:
-        ARM_ACCESS_KEY: ${{ steps.check_backend.outputs.accountKey }}
-      run: |
-        touch backend.tf
-        cat <<EOF > backend.tf
-        terraform {
-          backend "azurerm" {
-            storage_account_name = "vaaniravinderg01010"
-            container_name       = "containervaani"
-            key                  = "terraform.tfstate"
-          }
-        }
-        EOF
-        terraform init
+      - name: Terragrunt Validate
+        run: |
+          terragrunt run-all validate \
+           --terragrunt-working-dir $PWD/env/dev/ \
+           --terragrunt-include-external-dependencies \
+           --terragrunt-non-interactive
+        working-directory: ${{ github.workspace }}/infra  
 
-    - name: Terraform Validate
-      run: terraform validate
 
-    - name: Terraform Plan
-      env:
-        ARM_ACCESS_KEY: ${{ steps.check_backend.outputs.accountKey }}
-      id: tf-plan
-      run: |
-        export exitcode=0
-        terraform plan -detailed-exitcode -no-color -out tfplan || export exitcode=$?
-        echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
+  
+      # Generates an execution plan for Terraform
+      # An exit code of 0 indicated no changes, 1 a terraform failure, 2 there are pending changes.
+      - name: Terragrunt Plan
+        id: tf-plan
+        run: |
+          export exitcode=0
+          terragrunt run-all plan \
+          --terragrunt-working-dir $PWD/env/${{ inputs.environment }} \
+          -detailed-exitcode \
+          -no-color \
+          -out tfplan || export exitcode=$?
+          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
+  
+          find ./env -type f
+          bk=$(find ./env -type f -name '*backend.tf')
+          cat $bk
+          
+          if [ $exitcode -eq 1 ]; then
+            echo Terragrunt Plan Failed!
+            exit 1
+          else 
+            exit 0
+          fi
+        working-directory: ${{ github.workspace }}/infra
+
+
+      - name: Terragrunt Apply
+        id: tf-apply
+        run: |
+         echo "yes" | terragrunt run-all apply \
+         --terragrunt-working-dir $PWD/env/${{ inputs.environment }} \
+         -auto-approve \
+         -input=false \
+         -no-color \
+         tfplan
+        working-directory: ${{ github.workspace }}/infra
+
+      #- name: Install Terrascan
+      #  run: |
+      #    wget https://github.com/tenable/terrascan/releases/download/v1.18.1/terrascan_1.18.1_Linux_x86_64.tar.gz
+      #    tar xvzf terrascan_1.18.1_Linux_x86_64.tar.gz
+      #    sudo mv terrascan /usr/local/bin/
+
+      #- name: Run Terrascan
+      #  run: |
+      #   terrascan scan -i terraform -d ./ ts:minseverity=High
+      #  env:
+      #   TS_ALLOW_DOWNLOADS: "true"
+  
+      #- name: Install Terraform Linter
+      #  run: |
+      #   curl -sL https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
+      #  shell: bash
+   #
+      #   
+      #- name: Run Terraform Linter
+      #  run: |
+      #   tflint
+      #  env:
+      #    TF_VERSION: "1.3.1"
         
-        if [ $exitcode -eq 1 ]; then
-          echo Terraform Plan Failed!
-          exit 1
-        else 
-          exit 0
-        fi
-
-    - name: Terraform Show
-      id: show
-      shell: bash
-      run: terraform show -no-color tfplan 2>&1 > /tmp/plan.txt
-
-    - name: Terraform Apply
-      env:
-        ARM_ACCESS_KEY: ${{ steps.check_backend.outputs.accountKey }}
-      run: terraform apply -input=false tfplan
-      shell: bash
-
-    - name: Publish Terraform Plan
-      uses: actions/upload-artifact@v3
-      with:
-        name: tfplan
-        path: tfplan
-
-
-  # TO-DO:
-  # terrascan policy-as-codes
+         
+      # Save plan to artifacts  
+      - name: Publish Terraform Plan
+        uses: actions/upload-artifact@v3
+        with:
+          name: tfplan
+          path: tfplan
+  
